version: "2.1"

machine:
  node:
    version: 14.0.0

orbs:
  node: circleci/node@4.2.0

jobs:
  test:
    working_directory: ~/project
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: m2-yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - m2-yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: cd |
             ls | 
             ssh-keyscan 18.139.226.17 >> ~/.ssh/known_hosts |
             scp index.js ubuntu@18.139.226.17:/
workflows:
  test_my_app:
    jobs:
      - test