version: '2.1'

machine:
    node:
        version: 14.0.0

orbs:
  node: circleci/node@4.2.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
           name: Restore Yarn Package Cache
           keys:
             - m2-yarn-packages-{{ checksum "package.json" }}
      - node/install-packages:
          cache-path: ~/aws-server-nodejs/node_modules
          override-ci-command: npm install
      - run: npm run test

workflows:
  test_my_app:
    jobs:
      - test