version: '2.1'

machine:
    node:
        version: 14.0.0

orbs:
  node: circleci/node@4.2.0

jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - restore_cache:
           name: Restore Yarn Package Cache
           keys:
             - m2-yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run: 
          name: Install dependencies
          command: yarn install
      - save_cache:
           name: Save Yarn Package Cache
           key: m2-yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
           paths:
             - ./node_modules/
  

workflows:
  test_my_app:
    jobs:
      - test