version: "2.1"

machine:
  node:
    version: 14.0.0

orbs:
  node: circleci/node@4.2.0

jobs:
  test:
    working_directory: ~/project
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: m2-yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules/
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - m2-yarn-packages-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - add_ssh_keys:
          fingerprints:
            - "03:d7:bc:d2:7f:0a:50:90:43:1c:ba:14:72:b6:39:63"
      - run: cd |
          ls |
          ssh -o StrictHostKeyChecking=no index.js ubuntu@18.139.226.17 "ls"
workflows:
  test_my_app:
    jobs:
      - test
