version: '2.1'

orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '14'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
      - run:
          name: Deploy Over SSH
          command: |
            ssh ubuntu@ip-172-31-25-196 |


workflows:
  test_my_app:
    jobs:
      - test